//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("enlarge ver:0.4.21127.1")]
[assembly: AssemblyDescription("enlarges the current console window to the maximum size possible.")]
[assembly: AssemblyCompany("Bricksoft.com")]
[assembly: AssemblyProduct("enlarge")]
[assembly: AssemblyCopyright("Copyright (C) 2010-2012 Kody Brown.")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("951A8D2C-0724-46AE-8DCE-ECF07BF7C1E8")]
[assembly: AssemblyVersion("0.4.21127.1")]
[assembly: AssemblyFileVersion("0.4.21127.1")]


